account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import AccountLoginView

app_name = "account"

urlpatterns = [
    path("login/", AccountLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout")
]

books/urls.py
from django.urls import path

from books.views import BooksListView, BookDetailView, HomeView

urlpatterns = [
    path('', HomeView.as_view(), name="homepage"),
    path('books/', BooksListView.as_view(), name="books_list"),
    path('books/<int:pk>/', BookDetailView.as_view(), name="book_detail")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/models.py
from django.db import models

# Create your models here.

books/models.py
from django.conf import settings
from django.db import models


class Book(models.Model):
    class LanguageTypes(models.TextChoices):
        UZBEK = 'uzbek', 'Uzbek'
        RUSSIAN = 'russian', 'Russian'
        ENGLISH = 'english', 'English'

    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.FloatField()
    sales_price = models.PositiveSmallIntegerField(default=0)
    best_seller = models.BooleanField(default=False)
    pub_year = models.PositiveIntegerField(null=True)
    page_size = models.PositiveIntegerField()
    lang = models.CharField(max_length=50, choices=LanguageTypes.choices)
    file = models.FileField()
    image = models.ImageField()
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="books")
    author = models.ForeignKey("BookAuthor", on_delete=models.CASCADE, related_name="books")


class Category(models.Model):
    name = models.CharField(max_length=100)


class BookAuthor(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

account/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomAuthenticationForm(AuthenticationForm):
    pass

account/views.py
from django.contrib.auth.views import LoginView

from account.forms import CustomAuthenticationForm


class AccountLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = "account/login.html"

books/views.py
from django.views.generic import ListView, DetailView, TemplateView

from books.models import Book


class BaseView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        return context


class HomeView(ListView):
    queryset = Book.objects.order_by("-id")
    template_name = "home.html"
    context_object_name = "books"


class BooksListView(ListView):
    queryset = Book.objects.order_by("-id")
    template_name = "books/books.html"
    context_object_name = "books"


class BookDetailView(DetailView):
    queryset = Book.objects.all()
    template_name = "books/book_detail.html"
    context_object_name = "book"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     book_id = self.kwargs.get(self.pk_url_kwarg)
    #     context["first_book"] = Book.objects.first()
    #     context["book"] = Book.objects.filter(id=book_id).first()
    #     return context

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage' %}">Book store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books_list' %}">Books</a>
                </li>
            </ul>
            <form class="d-flex" role="search" action="" method="post">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">
                            <button type="button" class="btn btn-primary">Logout</button>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">
                            <button type="button" class="btn btn-success">Login</button>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">
                            <button type="button" class="btn btn-primary">Register</button>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/books/book_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ book.title }}</h1>
        <h2>Category: {{ book.category.name }}</h2>
        <h2>Description: {{ book.description }}</h2>
        <h2>Price: {{ book.price }}</h2>
        <h2>Publication year: {{ book.pub_year }}</h2>
        <h2>Page size: {{ book.page_size }}</h2>
        <h2>Language: {{ book.lang }}</h2>
        <h2>Author: {{ book.author.name }}</h2>
    </div>
{% endblock %}

templates/books/books.html
{% extends 'base.html' %}

{% block title %}
    HomePage
{% endblock %}

{% block content %}
    <div class="container custom-home">
        <div class="row">
            {% for book in books %}
                <div class="col-md-4 card border">
                    <div class="card border mb-4 box-shadow h-50">
                        <img class="card-img-top" src="{{ book.image.url }}" alt="Bu Yerda Rasm Bor!">
                        <div class="card-body">
                            <h5 class="card-title custom-title">
                                <a href="{% url 'book_detail' book.id %}">{{ book.title }}</a>
                            </h5>
                            {% if book.description|length > 80 %}
                                <p class="card-text">{{ book.description|slice:80 }}</p>
                            {% else %}
                                <p class="card-text">{{ book.description }}</p>
                            {% endif %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'book_detail' book.id %}" class="btn btn-sm btn-outline-secondary">
                                        More
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="card-group">
            {% for book in books %}
                <div class="card">
                    <img src="{{ book.image.url }}" class="card-img-top" alt="..." width="400" height="400">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p class="card-text">{{ book.desc }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">{{ book.pub_year }}</small>
                    </div>
                </div>
                <div class="card">
                    <img src="{{ book.image.url }}" class="card-img-top" alt="..." width="400" height="400">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p class="card-text">{{ book.desc }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">{{ book.pub_year }}</small>
                    </div>
                </div>
                <div class="card">
                    <img src="{{ book.image.url }}" class="card-img-top" alt="..." width="400" height="400">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p class="card-text">{{ book.desc }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">{{ book.pub_year }}</small>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}